use_frameworks!

target 'YoutubeVideoDownloader_Example' do
  pod 'YoutubeVideoLinkProcessor', :path => '../'
  inherit! :search_paths
  target 'YoutubeVideoDownloader_Tests' do
    inherit! :search_paths
  end
end
